export const CREATE_TASK = 'TASK/CREATE_TASK';
export const DELETE_TASK = 'TASK/DELETE_TASK';
export const UPDATE_TASK = 'TASK/UPDATE_TASK';
export const UPDATE_TASK_MODAL_OPEN = 'TASK/UPDATE_TASK_MODAL_OPEN';
export const UPDATE_TASK_MODAL_CLOSE = 'TASK/UPDATE_TASK_MODAL_CLOSE';
export const ARCHIVE_TASK = 'TASK/ARCHIVE_TASK';
export const PARAM_REDACT = 'TASK/PARAM_REDACT';

export const CHANGE_IS_ARCHIVED = 'TABLE/CHANGE_IS_ARCHIVED'
